### ISSUE TITLE
Download of recorded files?

### ISSUE THREAD

**Issue by roberthunt** [667bdrm/sofiactl#2]
Is it possible to download the recorded files? I can see that its possible to download log files and configuration, is there any way to download the actual recordings? The ActiveX plugin and XMeye have this facility but it is really slow. I would be nice to be able to automate it via a script if possible.

Thanks

**Comment by 667bdrm** [comment]
I have sniffed the communication of video stream playback, but doesn't get this after sending same commands with the my client. Maybe I missed something. Currently downloading through rtsp.

**Comment by 667bdrm** [comment]
UPD: Latest version has experimental support of recorded stream downloading.

Usage example:

./sofiactl.pl -u user -p pass -host 192.168.1.1 -port 34567 -c Download --bt 2019-12-30T20:05:48Z --et 2019-12-30T20:06:21Z --ch 1

The file should be downloaded with the same name as in internal fielsystem ('/' replaced to '_')
